import { Movie } from './types';

export const movies: Movie[] = [
  {
    id: '1',
    title: 'Oppenheimer',
    image: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    tags: ['Drama', 'Historie', 'Životopisný'],
    description: 'Příběh amerického vědce J. Roberta Oppenheimera a jeho role při vývoji atomové bomby.',
    releaseDate: '2023-07-20',
  },
  {
    id: '2',
    title: 'Barbie',
    image: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    tags: ['Komedie', 'Fantasy', 'Dobrodružný'],
    description: 'Barbie žije v dokonalém světě, dokud nezačne přemýšlet o skutečném světě a smrti.',
    releaseDate: '2023-07-20',
  },
  {
    id: '3',
    title: 'Titanic',
    image: 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
    tags: ['Drama', 'Romantický'],
    description: 'Epický milostný příběh Jacka a Rose, kteří se setkávají na palubě luxusního parníku Titanic během jeho osudné první plavby.',
    releaseDate: '1997-12-19',
  },
  {
    id: '4',
    title: 'Chudáčci',
    image: 'https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
    tags: ['Komedie', 'Drama', 'Fantasy'],
    description: 'Bella Baxter je mladá žena, která je přivedena zpět k životu doktorem Godwinem Baxterem.',
    releaseDate: '2024-01-25',
  },
  {
    id: '5',
    title: 'Napoleon',
    image: 'https://image.tmdb.org/t/p/w500/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg',
    tags: ['Historie', 'Drama', 'Válečný'],
    description: 'Osobní pohled na původ Napoleona a jeho rychlý, nemilosrdný vzestup k císařství.',
    releaseDate: '2023-11-23',
  },
  {
    id: '6',
    title: 'Wonka',
    image: 'https://image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
    tags: ['Fantasy', 'Rodinný', 'Komedie'],
    description: 'Příběh mladého Willyho Wonky a jeho dobrodružství před otevřením nejslavnější čokoládovny na světě.',
    releaseDate: '2023-12-07',
  },
  {
    id: '7',
    title: 'Maestro',
    image: 'https://image.tmdb.org/t/p/w500/kxj7rMco6RNYsVcNwuGAIlfWu64.jpg',
    tags: ['Drama', 'Životopisný', 'Hudební'],
    description: 'Komplexní příběh lásky mezi Leonardem Bernsteinem a Felicií Montealegre.',
    releaseDate: '2023-12-20',
  },
  {
    id: '8',
    title: 'Přání',
    image: 'https://image.tmdb.org/t/p/w500/ehumsuIBbgAe1hg343oszCLrAfI.jpg',
    tags: ['Animovaný', 'Rodinný', 'Fantasy'],
    description: 'Příběh o mladé dívce Ashe a magické říši, kde se přání mohou stát skutečností.',
    releaseDate: '2023-11-23',
  },
  {
    id: '9',
    title: 'Aquaman a ztracené království',
    image: 'https://image.tmdb.org/t/p/w500/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg',
    tags: ['Akční', 'Fantasy', 'Dobrodružný'],
    description: 'Aquaman musí ochránit Atlantidu před ekologickou katastrofou.',
    releaseDate: '2023-12-21',
  },
  {
    id: '10',
    title: 'Někdo klepe na dveře',
    image: 'https://image.tmdb.org/t/p/w500/rV56FkcHkzHJcBOOqoCeSDnoBff.jpg',
    tags: ['Horor', 'Thriller'],
    description: 'Rodina na dovolené čelí apokalyptické hrozbě od záhadných návštěvníků.',
    releaseDate: '2024-02-01',
  },
  {
    id: '11',
    title: 'Argylle',
    image: 'https://image.tmdb.org/t/p/w500/95VlSEfLMqeX36UVcHJuNlWEpwf.jpg',
    tags: ['Akční', 'Thriller', 'Komedie'],
    description: 'Špionážní thriller o nejlepším špionovi na světě s amnézií.',
    releaseDate: '2024-02-01',
  },
  {
    id: '12',
    title: 'Madame Web',
    image: 'https://image.tmdb.org/t/p/w500/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg',
    tags: ['Akční', 'Sci-Fi', 'Fantasy'],
    description: 'Příběh o původu jasnovidky Cassandry Webb a její spojení s pavučinou osudu.',
    releaseDate: '2024-02-14',
  },
  {
    id: '13',
    title: 'Matrix',
    image: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    tags: ['Akční', 'Sci-Fi', 'Thriller'],
    description: 'Thomas Anderson, známý také jako hacker Neo, odhaluje šokující pravdu o své realitě a připojuje se k povstání proti strojům ovládajícím lidstvo.',
    releaseDate: '1999-03-31',
  },
  {
    id: '14',
    title: 'Demon Slayer: Kimetsu no Yaiba - To the Hashira Training',
    image: 'https://image.tmdb.org/t/p/w500/iTGBHdL12QEpLyRVlykDuiYxzAG.jpg',
    tags: ['Animovaný', 'Akční', 'Fantasy'],
    description: 'Tanjiro se připojuje k intenzivnímu tréninku Hashira.',
    releaseDate: '2024-02-23',
  },
  {
    id: '15',
    title: 'Kung Fu Panda 4',
    image: 'https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
    tags: ['Animovaný', 'Akční', 'Komedie'],
    description: 'Po musí trénovat nového Dračího bojovníka a čelit nové hrozbě.',
    releaseDate: '2024-03-07',
  },
  {
    id: '16',
    title: 'Mission: Impossible – Odplata První část',
    image: 'https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    tags: ['Akční', 'Thriller'],
    description: 'Ethan Hunt a jeho tým čelí dosud nejnebezpečnější misi: vystopovat novou zbraň, která ohrožuje celé lidstvo.',
    releaseDate: '2023-07-12',
  }
];